# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9cfe12b62f00d16377bf13053dd156e8fa4dfc1d5f189293d2b58f8ec8dcc40c251441247b8e501a2dd4433101ca8208c27cd5cae1541a78592b4c697278546d

test:
  secret_key_base: 1d8651e27b3903ffe3e31efd81dda00d3bb25233d83650dae0917b43a60007f84e14042a95be180dccf2d07348619e540d093f1eafbe05dea517ff5345a5a8c0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
